In [2]:
import pandas as pd
df = pd.read_csv(
    r"C:\Users\gobinath\Downloads\SMSSpamCollection",
    sep="\t",
    header=None,
    names=["label", "message"],
    encoding="utf-8"
)

df.to_csv("spam.csv", index=False, encoding="utf-8")

print("CSV file created successfully!")
print(df.head())
print("Dataset shape:", df.shape)

CSV file created successfully!
  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
Dataset shape: (5572, 2)

In [3]:
df = pd.read_csv(
    "spam.csv"
)
df

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
# Count messages in each category
print(df["label"].value_counts())

label
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
df["message"]

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: message, Length: 5572, dtype: object

In [6]:
df["label"]

0        ham
1        ham
2       spam
3        ham
4        ham
        ...
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: label, Length: 5572, dtype: object

In [7]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(403)

In [32]:
deplicate=df[df.duplicated()]
#print(deplicate)
print("total number of duplicate : ",len(deplicate))
display(deplicate)

total number of duplicate :  403

     label                                            message
103    ham  As per your request 'Melle Melle (Oru Minnamin...
154    ham  As per your request 'Melle Melle (Oru Minnamin...
207    ham  As I entered my cabin my PA said, '' Happy B'd...
223    ham                             Sorry, I'll call later
326    ham                   No calls..messages..missed calls
...    ...                                                ...
5524  spam  You are awarded a SiPix Digital Camera! call 0...
5535   ham  I know you are thinkin malaria. But relax, chi...
5539   ham                         Just sleeping..and surfing
5553   ham                        Hahaha..use your brain dear
5558   ham                             Sorry, I'll call later

[403 rows x 2 columns]

In [10]:
deplicate1=df.duplicated()
deplicate1

0       False
1       False
2       False
3       False
4       False
        ...
5567    False
5568    False
5569    False
5570    False
5571    False
Length: 5572, dtype: bool

In [11]:
duplicates = df[df.duplicated(keep=False)]
print("Total rows marked as duplicates:", len(duplicates))
display(duplicates.head(10))  # use display function to continues as dataframe

Total rows marked as duplicates: 684

   label                                            message
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
7    ham  As per your request 'Melle Melle (Oru Minnamin...
8   spam  WINNER!! As a valued network customer you have...
9   spam  Had your mobile 11 months or more? U R entitle...
11  spam  SIX chances to win CASH! From 100 to 20,000 po...
12  spam  URGENT! You have won a 1 week FREE membership ...
45   ham                   No calls..messages..missed calls
62   ham                          Its a part of checking IQ
65  spam  As a valued customer, I am pleased to advise y...
66   ham  Today is "song dedicated day.." Which song wil...

In [12]:
df_clean = df.drop_duplicates().copy()
print("Original dataset shape:", df.shape)
print("Dataset shape after removing duplicates:", df_clean.shape)
print("Remaining duplicate rows:", df_clean.duplicated().sum())

Original dataset shape: (5572, 2)
Dataset shape after removing duplicates: (5169, 2)
Remaining duplicate rows: 0

In [13]:
df_clean["label"]

0        ham
1        ham
2       spam
3        ham
4        ham
        ...
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: label, Length: 5169, dtype: object

In [14]:
print(df_clean[["label", "message"]].head())

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [15]:
message = df_clean["message"].iloc[2]
print("Original message:")
print(message)
# Convert the message to lowercase
cleaned_message = message.lower()
print("\nLowercase message:")
print(cleaned_message)

Original message:
Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's

Lowercase message:
free entry in 2 a wkly comp to win fa cup final tkts 21st may 2005. text fa to 87121 to receive entry question(std txt rate)t&c's apply 08452810075over18's

In [16]:
message = df_clean["message"].iloc[2]

cleaned_message = message.lower()

print("Original message:")
print(message)

print("\nLowercase message:")
print(cleaned_message)
print("\nOriginal message in DataFrame:")
print(df_clean["message"].iloc[2])

Original message:
Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's

Lowercase message:
free entry in 2 a wkly comp to win fa cup final tkts 21st may 2005. text fa to 87121 to receive entry question(std txt rate)t&c's apply 08452810075over18's

Original message in DataFrame:
Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's

In [17]:
print("Dataset shape:", df_clean.shape)

print("\nSample messages:")
print(df_clean["message"].head())

print("\nMessage categories:")
print(df_clean["label"].value_counts())

Dataset shape: (5169, 2)

Sample messages:
0    Go until jurong point, crazy.. Available only ...
1                        Ok lar... Joking wif u oni...
2    Free entry in 2 a wkly comp to win FA Cup fina...
3    U dun say so early hor... U c already then say...
4    Nah I don't think he goes to usf, he lives aro...
Name: message, dtype: object

Message categories:
label
ham     4516
spam     653
Name: count, dtype: int64

## machine learning algorithm used to split data ...for training and testing part

In [18]:
from sklearn.model_selection import train_test_split

X = df_clean["message"]
y = df_clean["label"]
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training messages:", len(X_train))
print("Testing messages:", len(X_test))
print("\nTraining label counts:")
print(y_train.value_counts())
print("\nTesting label counts:")
print(y_test.value_counts())

Training messages: 4135
Testing messages: 1034

Training label counts:
label
ham     3613
spam     522
Name: count, dtype: int64

Testing label counts:
label
ham     903
spam    131
Name: count, dtype: int64

## it is one of NLP algorithm used to change the word to numarical values ......and add some weights

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

print("Training data shape:", X_train_tfidf.shape)
print("Testing data shape:", X_test_tfidf.shape)
print("Number of words/features:", len(vectorizer.get_feature_names_out()))

Training data shape: (4135, 7680)
Testing data shape: (1034, 7680)
Number of words/features: 7680

In [34]:
print(X_train_tfidf)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 54735 stored elements and shape (4135, 7680)>
  Coords	Values
  (0, 6620)	0.46972053147573545
  (0, 2121)	0.5494390936793128
  (0, 926)	0.27302453527471554
  (0, 3431)	0.28681222213960167
  (0, 1175)	0.32889978169730083
  (0, 1034)	0.22262669782699995
  (0, 7644)	0.14137598054893938
  (0, 6426)	0.2883706884664802
  (0, 7123)	0.24452632207532418
  (1, 7666)	0.3692015439831947
  (1, 3316)	0.36341476387791166
  (1, 4613)	0.19995964613324727
  (1, 4210)	0.37125568141268966
  (1, 1543)	0.5155024572995014
  (1, 4791)	0.21735204696568938
  (1, 2482)	0.37125568141268966
  (1, 915)	0.3209202571821429
  (2, 7644)	0.15846316312851633
  (2, 4869)	0.2845838793573964
  (2, 992)	0.4276147771423104
  (2, 4742)	0.2694958804038539
  (2, 4672)	0.3164797385708495
  (2, 6871)	0.15667199372011065
  (2, 1720)	0.4632054417386278
  (2, 7483)	0.2708972072041858
  :	:
  (4133, 6756)	0.15752910004873982
  (4133, 3112)	0.11975193769214103
  (4133, 3715)	0.09393421775014872
  (4133, 3596)	0.08683370000676796
  (4133, 6017)	0.14661952937663789
  (4133, 3150)	0.12551883881918846
  (4133, 4201)	0.12241337686518922
  (4133, 3214)	0.12225003038085541
  (4133, 3722)	0.126630743329268
  (4133, 6227)	0.10533490900433325
  (4133, 5277)	0.40098197235035615
  (4133, 3427)	0.17472635006457102
  (4133, 2924)	0.2028640372955401
  (4133, 3748)	0.23543493848369754
  (4133, 1270)	0.23543493848369754
  (4133, 883)	0.21488498782345308
  (4133, 7428)	0.24396393861602902
  (4133, 4859)	0.5119697782878839
  (4133, 1859)	0.25598488914394196
  (4133, 2451)	0.25598488914394196
  (4134, 7644)	0.15477871219725642
  (4134, 2273)	0.33479767151289197
  (4134, 3395)	0.3745457322521715
  (4134, 6428)	0.6015270417245551
  (4134, 6985)	0.6015270417245551

In [20]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

print("Spam detection model trained successfully!")

Spam detection model trained successfully!

In [21]:
y_pred = model.predict(X_test_tfidf)

print("First 10 actual labels:")
print(y_test.head(10).tolist())

print("\nFirst 10 predicted labels:")
print(y_pred[:10].tolist())

First 10 actual labels:
['ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham']

First 10 predicted labels:
['ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham']

## test the model accuracy

In [22]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", round(accuracy * 100, 2), "%")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Model Accuracy: 95.26 %

Classification Report:
              precision    recall  f1-score   support

         ham       0.95      1.00      0.97       903
        spam       1.00      0.63      0.77       131

    accuracy                           0.95      1034
   macro avg       0.97      0.81      0.87      1034
weighted avg       0.96      0.95      0.95      1034

Confusion Matrix:
[[903   0]
 [ 49  82]]

## test the new model

In [23]:
new_message = ["Congratulations! You won a FREE prize. Call now!"]

# Convert the message using our existing TF-IDF vectorizer
new_message_tfidf = vectorizer.transform(new_message)

# Predict the category
prediction = model.predict(new_message_tfidf)

print("Message:", new_message[0])
print("Prediction:", prediction[0])

Message: Congratulations! You won a FREE prize. Call now!
Prediction: spam

In [24]:
from sklearn.linear_model import LogisticRegression

# Create the model
lr_model = LogisticRegression(max_iter=1000)

# Train the model
lr_model.fit(X_train_tfidf, y_train)

print("Logistic Regression model trained successfully!")

Logistic Regression model trained successfully!

In [25]:
from sklearn.metrics import accuracy_score

# Naive Bayes predictions
nb_pred = model.predict(X_test_tfidf)

# Logistic Regression predictions
lr_pred = lr_model.predict(X_test_tfidf)

# Calculate accuracy
nb_accuracy = accuracy_score(y_test, nb_pred)
lr_accuracy = accuracy_score(y_test, lr_pred)

print("Naive Bayes Accuracy:", round(nb_accuracy * 100, 2), "%")
print("Logistic Regression Accuracy:", round(lr_accuracy * 100, 2), "%")

Naive Bayes Accuracy: 95.26 %
Logistic Regression Accuracy: 96.42 %

In [26]:
from sklearn.metrics import classification_report

print("=== Naive Bayes ===")
print(classification_report(y_test, nb_pred))

print("=== Logistic Regression ===")
print(classification_report(y_test, lr_pred))

=== Naive Bayes ===
              precision    recall  f1-score   support

         ham       0.95      1.00      0.97       903
        spam       1.00      0.63      0.77       131

    accuracy                           0.95      1034
   macro avg       0.97      0.81      0.87      1034
weighted avg       0.96      0.95      0.95      1034

=== Logistic Regression ===
              precision    recall  f1-score   support

         ham       0.96      1.00      0.98       903
        spam       0.96      0.75      0.84       131

    accuracy                           0.96      1034
   macro avg       0.96      0.87      0.91      1034
weighted avg       0.96      0.96      0.96      1034

In [27]:
import joblib

# Save the trained Logistic Regression model
joblib.dump(lr_model, "spam_model.pkl")

# Save the TF-IDF vectorizer
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

print("Model and vectorizer saved successfully!")

Model and vectorizer saved successfully!

In [28]:
import joblib

# Load the saved files
loaded_model = joblib.load("spam_model.pkl")
loaded_vectorizer = joblib.load("tfidf_vectorizer.pkl")

print("Saved model and vectorizer loaded successfully!")

# Test a new SMS message
new_message = ["Congratulations! You have won a FREE prize. Call now!"]

# Convert text into TF-IDF features
message_tfidf = loaded_vectorizer.transform(new_message)

# Predict the message category
prediction = loaded_model.predict(message_tfidf)

print("\nMessage:", new_message[0])
print("Prediction:", prediction[0])

Saved model and vectorizer loaded successfully!

Message: Congratulations! You have won a FREE prize. Call now!
Prediction: spam